name: Fetch Rain Data

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    # manual trigger
  schedule:
    - cron: '20 6 * * *'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@main
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
    - name: Set up Python 3.10
      uses: actions/setup-python@main
      with:
        python-version: "3.10"
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get Data
      run: |
        python realtime-water_07.02.py
    - name: Upload Data
      uses: actions/upload-artifact@main
      with:
        name: Fetched_Data
        path: data
        